#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'

cookbook 'networking_basic'
cookbook "curl",
  :path => "cookbooks-src/curl"

cookbook "postgresql"

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git'
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv'
cookbook 'apt',
  :git => 'https://github.com/opscode-cookbooks/apt'
cookbook 'unicorn'
cookbook 'nginx'
cookbook 'runit'
cookbook 'rails-lastmile',
  :git => 'git://github.com/DanThiffault/rails-lastmile.git'
