development:
  adapter: postgresql
  encoding: unicode
  database: bigode-ng_development
  pool: 5
  username: pedrovanzella
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bigode-ng_test
  pool: 5
  username: pedrovanzella
  password:
